name: Pytest

on:
  - push
  - pull_request

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install system packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y swig libpcsclite-dev

      - uses: actions/setup-python@v4
        with:
          python-version-file: .github/workflows/.python-version
          cache: pip
          cache-dependency-path: "**/pyproject.toml"

      - name: Install Python dependencies
        run: pip install -e .[test]

      - name: Run tests
        run: ./tests/run.sh

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./tests/coverage
